import {useState} from "react";

export default function AICommandAgent(){
 const [input,setInput]=useState("set time to night");
 const [command,setCommand]=useState("/time set night");
 const generate=()=>{
  const text=input.toLowerCase();
  if(text.includes("night")) setCommand("/time set night");
  else if(text.includes("day")) setCommand("/time set day");
  else setCommand("/say Command generated by AI Agent");
 };
 return <section className="ai-command-agent">
  <div className="ai-header">🤖 AI COMMAND AGENT</div>
  <p>Your Minecraft command assistant</p>
  <input value={input} onChange={e=>setInput(e.target.value)} placeholder="Describe your command..." />
  <button onClick={generate}>Generate Command</button>
  <pre>{command}</pre>
  <div className="ai-actions"><button>Copy</button><button>Fix</button><button>Explain</button><button>Save</button></div>
 </section>;
}
